apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres/secret.yml
  - postgres/statefulset.yml
  - postgres/service.yml

  - shopflow/configmap.yml
  - shopflow/secret.yml
  - shopflow/deployment.yml
  - shopflow/service.yml