apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shopflow-dev
type: Opaque
stringData:
  POSTGRES_PASSWORD: "devpassword123"
  POSTGRES_USER: "shopflow"
  POSTGRES_DB: "shopflow"