apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: postgres
  namespace: shopflow-dev
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef: 
                name: postgres-secret
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "shopflow"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "shopflow"
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources: 
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - "ReadWriteOnce" # read write by a single node
        resources:
          requests:
            storage: 1Gi
          

            